server:
  port: 9000
logging:
  level:
    root: INFO
springdoc:
  api-docs:
    path: /api-docs
    
props:
  ignore-path: >
    login/login, 
    "favicon.ico", 
    test/*, 
    api-docs/*, 
    swagger-ui/*
  uri-prefix: "/api/"