server:
  port: 9000
logging:
  level:
    root: INFO
springdoc:
  api-docs:
    path: /api-docs
    
props:
  ignore-path: >
    login/login, 
    "favicon.ico", 
    test/*, 
    api-docs/*, 
    swagger-ui/*,
    user/*
  uri-prefix: "/api/"
  aTokenTime: 60000 # 1분
  rTokenTime: 1800000 # 30분
#1000L * 60 * 60; // 60분